### ISSUE TITLE
v1.x Milestone

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#2488]
We will be releasing minor versions more frequently, and this will be a record of the most significant changes for each minor version in order to reduce confusion.

- v1.1
  - [x] Temporarily removed code conversion codeLens #2444
  - [x] Preview features extracted to [Vue and Nuxt Preview](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-vue-preview)
- v1.2
  - [x] Upgrade the dependent core framework version to be compatible with upstream [Monaco integration](https://github.com/volarjs/volar.js/pull/10)
 - v1.3 (pre-release) ~ v1.4
   - [x] #2475
   - [x] Upgrade the dependent Plugin API version https://github.com/volarjs/volar.js/issues/14
   - [x] #2489
 - v1.5 (pre-release) ~ v1.6
   - [x] #2677
   - [x] #2685
   - [x] Rename settings from `volar.*` to `vue.*`
 - v1.7 (pre-release) ~ v1.8
   - [x] Scripts API
   - [x] #2437
   - [x] Migrating from `@volar-plugins/*` to `volar-service-*`
 - v1.9 (pre-release) ~ v2.0
   - [ ] Support plugins via external extension contributions
   - [ ] Rules API

**Comment by johnsoncodehk** [comment]
Updated the roadmap, the next official version after v1.6 is v2.0.

**Comment by jd-solanki** [comment]
Will you make minor releases for bug fixes or we have to wait for v2 for reported bug fixes?

**Comment by johnsoncodehk** [comment]
We have at least one more v1.6.2.
