### ISSUE TITLE
Known TS Plugin integration regressions

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#3912]
- [x] ~~When modifying the script block lang attr, an internal error occurs in the tsserver due to the script kind change in the .vue file. This may need to wait for TypeScript to fix it.~~ Fixed by https://github.com/microsoft/TypeScript/pull/57641
- [x] Vue Language Server's semantic tokens (component tag) and tsserver's semantic tokens cannot coexist. #3915
- [x] When multiple tsservers are started (perhaps due to opening multiple IDEs or multiple workspaces), the Vue language server can only communicate with the last started tsserver. #3916
- [x] #3914
- [x] The following code should to TS Plugin #3917 https://github.com/vuejs/language-tools/blob/a918fcd940dfe73c6f82b4e42ffd2691fd80f3fe/packages/language-service/lib/plugins/typescript.ts#L37-L175 
- [x] Plugin API v2 #3918
- [x] ~~jsconfig/tsconfig is required #3942~~ External bug: https://github.com/microsoft/TypeScript/issues/57630
- [ ] VSCode 1.88.0 is required #3962
